apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibelang-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: vibelang

  template:
    metadata:
      labels:
        app: vibelang

    spec:
      containers:
        - name: vibelang
          image: vibelang-app:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"
          ports:
            - containerPort: 5000